name: build Docker

on: workflow_dispatch


env:
  IMAGE_NAME: metaops/simple-kubernetes-webhook


jobs:
  build-server:
    runs-on: self-hosted  

    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}    

    - name: create latest tag if its the main branch
      if:  ${{ env.RELEASE_VERSION == 'main' }}
      run: echo "DOCKER_TAG=latest" >> $GITHUB_ENV  

    - name: create git tag if its the build uses tag
      if:  ${{ env.RELEASE_VERSION != 'main' }}
      run: echo "DOCKER_TAG=${{ env.RELEASE_VERSION }}" >> $GITHUB_ENV  

    - name: Build docker image 
      run:  docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}

    - name: docker login
      if: github.event_name != 'pull_request'
      run: docker login $DOCKER_REGISTRY -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD

    - name: docker push container
      if: github.event_name != 'pull_request'
      run: docker push ${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}


